# Generated by Django 4.2.7 on 2023-12-04 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_league_match'),
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='recentDeck',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.deck'),
        ),
        migrations.AddField(
            model_name='profile',
            name='recentFlavor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.flavor'),
        ),
        migrations.AddField(
            model_name='profile',
            name='recentFormat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mtgformat'),
        ),
    ]
