# Generated by Django 4.2.7 on 2023-11-29 09:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Archetype')),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='deck name')),
                ('dateCreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('archetype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.archetype')),
            ],
        ),
        migrations.CreateModel(
            name='MtgFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='none', max_length=30)),
                ('isdefault', models.BooleanField(default=False, verbose_name='default')),
                ('deck', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flavors', to='core.deck')),
            ],
        ),
        migrations.AddField(
            model_name='deck',
            name='mtgFormat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mtgformat'),
        ),
        migrations.AddField(
            model_name='archetype',
            name='mtgFormat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mtgformat'),
        ),
    ]
