# Generated by Django 4.2.7 on 2023-11-30 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('isFinished', models.BooleanField(default=False, verbose_name='finished')),
                ('mtgFormat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mformat', to='core.mtgformat')),
                ('myDeck', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mydeckl', to='core.deck')),
                ('myFlavor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='myflavorl', to='core.flavor')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('theirName', models.CharField(max_length=100, null=True)),
                ('inLeagueNum', models.IntegerField(null=True)),
                ('game1', models.BooleanField(default=None, help_text='win', null=True, verbose_name='Win1')),
                ('game2', models.BooleanField(default=None, null=True, verbose_name='Win2')),
                ('game3', models.BooleanField(default=None, null=True, verbose_name='Win3')),
                ('didjawin', models.BooleanField(default=None, null=True, verbose_name='Match Win')),
                ('league', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='core.league')),
                ('mtgFormat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mtgFormat', to='core.mtgformat')),
                ('myDeck', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mydeck', to='core.deck')),
                ('theirArchetype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='theirarchetype', to='core.archetype', verbose_name='Their Archetype')),
                ('theirDeck', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='theirdeck', to='core.deck', verbose_name='Their Deck')),
                ('theirFlavor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='theirflavors', to='core.flavor', verbose_name='Thier Flavor')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
